# Generated by Django 2.1.7 on 2019-02-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_person_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Salary',
            new_name='salary',
        ),
    ]
